// One-time migration of the supplied public pages; business data remains the source.
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const write = (p, s) => fs.writeFileSync(path.join(root, p), s);
const context = {window:{}}; vm.createContext(context); vm.runInContext(read('js/data.js'),context);
const data = context.window.NALLAYIL_DATA;
const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo = '<img src="images/brand/nallayil-ayurveda-logo.jpg" width="960" height="960" alt="Nallayil Ayurveda" class="brand-image">';
function nav(active) { return `<a href="#main" class="skip-link">Skip to content</a><header class="site-header"><div class="container nav-container"><a href="index.html" class="brand-logo" aria-label="Nallayil Ayurveda home">${logo}</a><nav class="nav-menu" aria-label="Main navigation">${[['Home','index.html'],['About','index.html#about'],['Treatments','treatments.html'],['Gallery','gallery.html'],['Contact','index.html#contact']].map(([t,u])=>`<a href="${u}" ${active===t?'aria-current="page"':''}>${t}</a>`).join('')}</nav><div class="nav-actions"><a href="booking.html" class="btn btn-outline btn-book-nav">Book Appointment <span aria-hidden="true">↗</span></a><button class="mobile-toggle icon-button" aria-label="Open navigation" aria-controls="mobile-navigation" aria-expanded="false"><span></span><span></span></button></div></div></header><div class="drawer-overlay"></div><aside id="mobile-navigation" class="mobile-drawer" role="dialog" aria-modal="true" aria-label="Navigation" inert><div class="drawer-header">${logo}<button class="drawer-close icon-button" aria-label="Close navigation">×</button></div><nav class="drawer-nav" aria-label="Mobile navigation">${[['Home','index.html'],['About','index.html#about'],['Treatments','treatments.html'],['Gallery','gallery.html'],['Our centers','index.html#centers'],['Contact','index.html#contact']].map(([t,u])=>`<a href="${u}">${t}<span aria-hidden="true">↗</span></a>`).join('')}</nav><a href="booking.html" class="btn btn-outline">Book Appointment</a><a href="tel:+919961003718" class="drawer-phone">+91 99610 03718</a></aside>`; }
const footer = `<footer class="site-footer"><div class="container footer-top"><div><a class="brand-logo" href="index.html">${logo}</a><p>Traditional wisdom.<br>Thoughtful care. Naturally.</p></div><div><h3>Discover Nallayil</h3><a href="index.html#about">Our approach</a><a href="treatments.html">Treatments</a><a href="gallery.html">Gallery</a><a href="index.html#doctors">Our physicians</a><a href="index.html#offers">Wellness programmes</a></div><div><h3>We’re here to help</h3><a href="tel:+919961003718">+91 99610 03718</a><a href="mailto:manjeri@nallayilayurveda.com">manjeri@nallayilayurveda.com</a><a href="https://wa.me/919961003718" target="_blank" rel="noopener">Talk to us on WhatsApp ↗</a><a href="booking.html">Request an appointment</a></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Nallayil Ayurveda Hospital &amp; Ayur Home</span><span>Manjeri · Perinthalmanna · Ramanattukara</span></div></footer>`;
const head = (title,description)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Nallayil Ayurveda</title><meta name="description" content="${description}"><meta name="theme-color" content="#087A24"><link rel="icon" href="images/brand/nallayil-ayurveda-logo.jpg"><link rel="stylesheet" href="css/fonts.css"><link rel="stylesheet" href="css/style.css"><link rel="stylesheet" href="css/premium.css"></head>`;
const scripts = '<script defer src="js/data.js"></script><script defer src="js/main.js"></script>';
const lightbox = `<div class="modal" id="gallery-modal" role="dialog" aria-modal="true" aria-labelledby="gallery-modal-title" hidden><div class="modal-content gallery-lightbox"><button class="modal-close icon-button" aria-label="Close image">×</button><div class="lightbox-image"><img id="gallery-modal-img" alt=""></div><div class="lightbox-caption"><div><span id="gallery-counter" class="eyebrow"></span><h2 id="gallery-modal-title"></h2><p id="gallery-modal-desc"></p></div><div class="lightbox-controls"><button class="icon-button gallery-prev" aria-label="Previous image">←</button><button class="icon-button gallery-next" aria-label="Next image">→</button></div></div></div></div>`;
const img = (src,alt,cls='')=>`<img src="${esc(src)}" alt="${esc(alt)}" class="${cls}" loading="lazy" decoding="async" width="900" height="700">`;
const final = `<section class="final-wellness" id="contact"><div class="container"><span class="eyebrow">A NEW CHAPTER OF WELLBEING</span><h2>Begin your journey<br><em>towards natural wellness.</em></h2><p>A conversation is a lovely place to start.<br>Our team will help you find the right next step.</p><div class="hero-actions"><a href="tel:+919961003718" class="btn btn-primary">Contact Us <span aria-hidden="true">↗</span></a><a href="booking.html" class="text-link">Book an Appointment ↗</a></div></div></section>`;
const home = `${head('Kerala wisdom. Natural wellbeing.','Discover personal Ayurvedic care, Marma Chikitsa, Panchakarma and residential wellbeing at Nallayil Ayurveda in Kerala.')}<body class="home-page">${nav('Home')}<div class="scroll-progress" aria-hidden="true"><span></span></div><main id="main">
<section class="home-hero"><div class="container hero-grid"><div class="hero-copy"><div class="eyebrow">NALLAYIL AYURVEDA · KERALA</div><h1>Ancient wisdom.<br><em>A natural way<br>to wellbeing.</em></h1><p>Discover the gentle art of Kerala Ayurveda. Personal care, rooted in tradition and shaped around you.</p><div class="hero-actions"><a href="treatments.html" class="btn btn-primary">Explore Treatments <span aria-hidden="true">↗</span></a><a href="booking.html" class="text-link">Book Appointment</a></div><div class="hero-note"><span class="botanical-mark" aria-hidden="true">✳</span><span>Hospital &amp; Ayur Home<br><small>Manjeri · Perinthalmanna · Ramanattukara</small></span></div></div><figure class="hero-visual"><img src="images/massage-ritual.jpg" alt="An Ayurvedic herbal bolus massage with warm oil and skilled hands" width="678" height="452" fetchpriority="high"><figcaption><span>THE ART OF AYURVEDIC CARE</span><span>01 / KERALA TRADITIONS</span></figcaption><div class="hero-image-note">A slower pace.<br>A deeper sense of care.</div></figure></div><div class="container hero-bottom"><span>ROOTED IN KERALA. CENTERED ON YOU.</span><a href="#about">Take a moment. Explore below <span aria-hidden="true">↓</span></a></div></section>
<section class="home-section" id="about"><div class="container split about-layout"><div class="section-intro"><span class="eyebrow">01 / OUR STORY</span><h2>Care that begins<br>with <em>listening.</em></h2></div><div><p class="lead">A tradition of healing.<br>A personal approach to your wellbeing.</p><p>Nallayil Ayurveda brings together classical Kerala practice and focused clinical care across Malappuram and Kozhikode. Each journey begins with an attentive consultation and a thoughtful path back to balance.</p><div class="about-notes"><span>Marma &amp; Panchakarma</span><span>Hospital &amp; residential care</span><span>Personal treatment plans</span></div><a href="#doctors" class="text-link">Meet our physicians ↗</a></div></div></section>
<section class="philosophy-section" id="essence"><div class="container philosophy-layout"><div class="ritual-column"><div class="ritual-sticky"><span class="eyebrow">THE ELEMENTS OF CARE</span><div id="webgl-stage" class="webgl-stage" aria-label="A brass oil bowl, natural stones and herbal leaves on a wooden treatment tray" role="img"><img id="treatment-fallback" src="images/ritual-fallback.svg" alt="" width="720" height="600"></div><div class="ritual-caption"><span>Warm oil. Herbal wisdom. Gentle touch.</span><span aria-hidden="true">✳</span></div></div></div><div class="philosophy-story"><article class="philosophy-step"><span class="eyebrow">02 / THE AYURVEDIC WAY</span><h2>Rooted in nature.<br><em>Guided by tradition.</em></h2><p>Ayurveda considers the relationship between body, mind, nourishment and rest. At Nallayil, that understanding shapes an individual approach to care.</p></article><article class="philosophy-step"><span class="eyebrow">A CONSIDERED RHYTHM</span><h2>Small rituals.<br><em>Thoughtful care.</em></h2><p>Warm herbal oils, traditional bodywork and skilled hands come together with a quieter daily rhythm. Every treatment starts with a consultation.</p><a href="treatments.html" class="text-link">Discover our approach ↗</a></article></div></div></section>
<section class="home-section" id="treatments"><div class="container"><div class="section-heading"><div><span class="eyebrow">03 / TREATMENTS &amp; THERAPIES</span><h2>Traditional care.<br><em>For the life you live.</em></h2></div><a href="treatments.html" class="text-link">Explore all treatments ↗</a></div><div class="treatment-list">${data.treatments.slice(0,4).map((t,i)=>`<a class="treatment-row" href="treatments.html#${t.id}"><span class="treatment-num">0${i+1}</span><h3>${esc(t.title)}</h3><p>${esc(t.shortDesc)}</p><span class="round-arrow" aria-hidden="true">↗</span></a>`).join('')}</div></div></section>
<section class="experience" id="ritual"><div class="container experience-grid"><figure class="experience-visual">${img('images/massage-ritual.jpg','Traditional warm herbal bolus massage')}</figure><div class="experience-copy"><span class="eyebrow">04 / THE NALLAYIL EXPERIENCE</span><h2>Healing through<br><em>ancient touch.</em></h2><p>Warm herbal oil. The care of skilled hands. Time to pause. Discover a treatment experience grounded in Kerala’s Ayurvedic traditions.</p><a href="gallery.html" class="text-link">Explore the experience ↗</a></div></div></section>
<section class="home-section" id="knowledge"><div class="container"><div class="section-heading"><div><span class="eyebrow">05 / NATURAL HEALING</span><h2>Nature, in its<br><em>most thoughtful form.</em></h2></div><p>Traditional preparations and everyday rituals, selected with your care in mind.</p></div><div class="ingredient-grid"><article><span class="ingredient-symbol" aria-hidden="true">❧</span><span class="eyebrow">01 / BOTANICALS</span><h3>Herbal preparations</h3><p>Kashayams, oils and churnams informed by traditional Ayurvedic knowledge.</p></article><article><span class="ingredient-symbol oil-symbol" aria-hidden="true">◒</span><span class="eyebrow">02 / BODYWORK</span><h3>Warm medicinal oil</h3><p>Thoughtfully applied oils accompany traditional bodywork and restorative therapies.</p></article><article><span class="ingredient-symbol" aria-hidden="true">☼</span><span class="eyebrow">03 / DAILY RHYTHM</span><h3>Rest &amp; nourishment</h3><p>A considered stay, Ayurvedic meals and a gentle routine support the therapeutic process.</p></article></div></div></section>
<section class="home-section alt" id="gallery"><div class="container"><div class="section-heading"><div><span class="eyebrow">06 / AYURVEDA IN FOCUS</span><h2>Moments of <em>stillness.</em><br>Spaces for care.</h2></div><a href="gallery.html" class="text-link">View the gallery ↗</a></div><div class="gallery-grid home-gallery" id="dynamic-gallery-grid" data-limit="4"></div><p class="image-credit">Ayurvedic care and wellness imagery from the existing Nallayil collection.</p></div></section>
<section class="home-section" id="centers"><div class="container"><div class="section-heading"><div><span class="eyebrow">07 / OUR KERALA CENTERS</span><h2>Care, closer<br><em>to you.</em></h2></div><p>Three centers. One shared philosophy of personal, attentive Ayurvedic care.</p></div><div class="location-grid">${data.branches.map((b,i)=>`<article class="location"><span class="eyebrow">0${i+1} / ${esc(b.district)}</span><h3>${esc(b.name)}</h3><p>${esc(b.address)}</p><small>${esc(b.timing)}</small><div class="location-links"><a class="text-link" href="https://www.google.com/maps/search/?api=1&amp;query=${b.mapQuery}" target="_blank" rel="noopener">Get directions ↗</a><a href="tel:${b.phone.replace(/\s/g,'')}" aria-label="Call ${esc(b.name)}">Call ↗</a></div></article>`).join('')}</div></div></section>
<section class="home-section alt" id="doctors"><div class="container"><div class="section-heading"><div><span class="eyebrow">THE PEOPLE BEHIND YOUR CARE</span><h2>Knowledge, with<br><em>a human touch.</em></h2></div></div><div class="physician-list">${data.doctors.map(d=>`<article><div><h3>${esc(d.name)}</h3><p>${esc(d.qualification)}</p></div><div><p>${esc(d.specialty)}</p><small>${esc(d.branch)}</small></div><a href="booking.html?doctor=${encodeURIComponent(d.name)}" class="text-link">Enquire ↗</a></article>`).join('')}</div></div></section>
<section class="home-section testimonials-section" id="testimonials"><div class="container trust-grid"><div><span class="eyebrow">08 / PATIENT VOICES</span><h2>A little care.<br><em>A lasting impression.</em></h2><p>Experiences shared by the Nallayil community. Individual treatment experiences vary.</p><div class="slider-controls"><button class="icon-button slider-prev" aria-label="Previous testimonial">←</button><button class="icon-button slider-next" aria-label="Next testimonial">→</button></div></div><div class="testimonials-slider" aria-label="Patient testimonials" aria-live="polite">${data.testimonials.map((t,i)=>`<figure class="testimonial-card-wrap ${i===0?'active':''}" ${i?'hidden':''}><span class="quote-mark" aria-hidden="true">“</span><blockquote>${esc(t.comment)}</blockquote><figcaption><strong>${esc(t.name)}</strong><span>${esc(t.place)} · ${esc(t.condition)}</span></figcaption></figure>`).join('')}</div></div></section>
<section class="home-section alt" id="offers"><div class="container"><span class="eyebrow">SEASONAL CARE</span><h2>Time for <em>restoration.</em></h2><div id="dynamic-offers-grid" class="offers-list"></div></div></section>
<section class="home-section" id="faq"><div class="container faq-layout"><div><span class="eyebrow">09 / BEFORE YOUR VISIT</span><h2>A few helpful<br><em>answers.</em></h2></div><div class="faq-list">${[
['What makes Marma Chikitsa unique at Nallayil?','Marma Chikitsa is a specialised Kerala discipline centred around vital points connecting nerves, muscles and bones. Our doctors use measured pressure and therapeutic preparations as part of a considered care plan.'],
['How do I request an appointment?','Choose your center, physician and preferred date and time, then review and send your request on WhatsApp. Reception will confirm availability and your appointment. You can also call +91 99610 03718.'],
['Can I stay at Perinthalmanna Ayur Home?','Ayur Home in Pacheerippara, Pattikkad offers residential in-patient care with traditional cottages, doctor and nursing support, Ayurvedic meals and treatment suites. Contact our team to discuss your stay.'],
['Can I consult from outside Kerala?','Nallayil offers video consultations for patients across India and abroad. Select Online Video Consultation when making your request; our team will help arrange the next step.']
].map(([q,a])=>`<details class="faq-item"><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>${final}</main>${footer}${lightbox}${scripts}<script defer src="js/immersive.js"></script></body></html>`;
write('index.html',home);
write('gallery.html',`${head('A glimpse into Ayurvedic care','Explore the existing Nallayil Ayurveda gallery of treatments, herbal care and wellness.')}<body>${nav('Gallery')}<main id="main"><section class="page-hero"><div class="container"><span class="eyebrow">THE NALLAYIL COLLECTION</span><h1>Moments of care.<br><em>A sense of calm.</em></h1><p>Explore Ayurvedic treatments, herbal traditions and the spaces that inspire wellbeing.</p></div></section><section class="home-section gallery-section"><div class="container"><div class="filter-tabs" aria-label="Gallery categories">${['All',...new Set(data.initialGallery.map(g=>g.category))].map((c,i)=>`<button class="filter-btn gallery-filter-btn ${i===0?'active':''}" data-cat="${esc(c)}" aria-pressed="${i===0}">${c==='All'?'All photographs':esc(c)}</button>`).join('')}</div><p id="gallery-status" class="sr-only" role="status"></p><div class="gallery-grid" id="dynamic-gallery-grid"></div><p class="image-credit">Ayurvedic care and wellness imagery from the existing Nallayil collection.</p></div></section>${final}</main>${footer}${lightbox}${scripts}</body></html>`);
write('treatments.html',`${head('Treatments & therapies','Explore all eight existing Nallayil Ayurveda treatment specialties, from Marma and Panchakarma to rehabilitation and wellbeing.')}<body>${nav('Treatments')}<main id="main"><section class="page-hero"><div class="container"><span class="eyebrow">TRADITIONAL KERALA AYURVEDA</span><h1>A personal path<br><em>to wellbeing.</em></h1><p>Explore our treatment specialties. Your physician will recommend an approach and duration following your consultation.</p></div></section><section class="home-section"><div class="container"><div class="filter-tabs" aria-label="Treatment categories">${['all',...new Set(data.treatments.map(t=>t.category))].map((c,i)=>`<button class="filter-btn treatment-filter-btn ${i===0?'active':''}" data-category="${esc(c)}" aria-pressed="${i===0}">${c==='all'?'All treatments':esc(c)}</button>`).join('')}</div><p id="treatment-status" class="sr-only" role="status"></p><div class="treatment-details">${data.treatments.map((t,i)=>`<article class="treatment-detail-card" id="${t.id}" data-category="${esc(t.category)}"><div class="treatment-detail-number">0${i+1}</div><div class="tdc-body"><span class="eyebrow">${esc(t.category)}</span><h2>${esc(t.title)}</h2><p>${esc(t.shortDesc)}</p><details class="treatment-more"><summary>Explore this treatment <span aria-hidden="true">+</span></summary><ul>${t.benefits.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><p>Typical programme: ${esc(t.duration)}. Your care plan is determined at consultation.</p></details><a href="booking.html?treatment=${encodeURIComponent(t.id)}" class="text-link">Discuss your care ↗</a></div><div class="tdc-img-wrap">${img(t.image,t.title)}</div></article>`).join('')}</div></div></section>${final}</main>${footer}${scripts}</body></html>`);
let booking=read('booking.html');
booking=booking.replace(/<head>[\s\S]*?<\/head>/,head('Request an appointment','Request a consultation at Nallayil Ayurveda. Choose your preferred center, doctor and time; reception confirms your appointment on WhatsApp.').split('<html lang="en">')[1]);
booking=booking.replace(/<body>[\s\S]*?(?=<!-- Main Booking Area -->)/,`<body>${nav('')}`);
booking=booking.replace('<main class="booking-section"','<main id="main" class="booking-section"');
booking=booking.replace(/<footer class="site-footer">[\s\S]*?<\/footer>/,footer);
const replacements={
 'Real-Time Availability':'LET’S PLAN YOUR VISIT','Doctor Consultation Slot Booking':'Your first step towards wellbeing.',
 'Select Appointment Details':'Request a personal consultation','Slots are automatically synced with each doctor\'s clinical timetable.':'Choose a preferred time. Reception will confirm availability after you send your request on WhatsApp.',
 'Available Time Slots *':'Preferred Time *','Confirm Appointment Slot':'Review Appointment Request','Appointment Confirmed':'Your request is ready',
 'Nallayil Ayurveda Booking Slip':'Nallayil Ayurveda Appointment Request','Slot Reserved Successfully':'Awaiting reception confirmation',
 'Your appointment has been registered in our clinic management system. Please arrive 15 minutes before your scheduled slot.':'Your request has not been sent yet. Select “Send request on WhatsApp” below, then send the message to reception. Your appointment is confirmed only when reception replies.',
 'Send to WhatsApp':'Send request on WhatsApp','Print Slip':'Print Request','No upfront payment required • Pay consultation fee at clinic reception':'No payment is collected online. Reception will confirm the consultation details.',
 'min-width: 280px;':'max-width:100%;','NAL-2026-0000':'—'};
for(const [a,b] of Object.entries(replacements)) booking=booking.split(a).join(b);
booking=booking.replace('id="booking-receipt-modal"','id="booking-receipt-modal" role="dialog" aria-modal="true" aria-label="Review appointment request" hidden');
booking=booking.replace('<input type="tel" id="booking-phone"','<input autocomplete="tel" maxlength="22" type="tel" id="booking-phone"').replace('<input type="text" id="booking-name"','<input autocomplete="name" maxlength="100" type="text" id="booking-name"').replace('<input type="email" id="booking-email"','<input autocomplete="email" maxlength="150" type="email" id="booking-email"').replace('id="booking-gender"','id="booking-gender" aria-label="Gender"').replace('<option value="Male">','<option value="">Prefer not to say</option><option value="Male">');
booking=booking.replace('id="booking-notes"','id="booking-notes" maxlength="500"');
booking=booking.replace('<div style="text-align:center; margin-top:36px;">','<p class="privacy-note">Your details stay on this page until you choose to share them on WhatsApp. Only the appointment details needed by reception are included; please discuss medical reports directly with your physician.</p><p id="booking-error" role="alert" class="form-error"></p><div style="text-align:center; margin-top:36px;">');
booking=booking.replace(/<i class="[^"]*"[^>]*><\/i>/g,'').replace(/target="_blank"/g,'target="_blank" rel="noopener"');
write('booking.html',booking);
// No sample patient records in the public data file; preserve the internal store API.
let source=read('js/data.js').replace(/  initialBookings: \[[\s\S]*?\n  testimonials:/,'  initialBookings: [],\n\n  testimonials:');
write('js/data.js',source);
console.log('Redesigned four public pages using the existing business content.');
